#model2mc palette profile
#Sat Aug 29 12:24:01 CST 2026
minecraft\:acacia_leaves=\#2a5526
minecraft\:acacia_planks=\#b25e35
minecraft\:amethyst_block=\#8461d1
minecraft\:ancient_debris=\#68463d
minecraft\:andesite=\#888889
minecraft\:azalea_leaves=\#466e32
minecraft\:bamboo_planks=\#caab6c
minecraft\:basalt=\#46464a
minecraft\:birch_leaves=\#466a31
minecraft\:birch_planks=\#c1b48f
minecraft\:black_concrete=\#080a0f
minecraft\:black_glazed_terracotta=\#431e20
minecraft\:black_terracotta=\#251710
minecraft\:black_wool=\#1e1b1b
minecraft\:blackstone=\#2c272e
minecraft\:blue_concrete=\#2c2e8f
minecraft\:blue_terracotta=\#4a3c5b
minecraft\:blue_wool=\#253192
minecraft\:bone_block=\#dbd6b5
minecraft\:bricks=\#915850
minecraft\:brown_concrete=\#603b1f
minecraft\:brown_mushroom_block=\#947052
minecraft\:brown_terracotta=\#4d3324
minecraft\:brown_wool=\#835432
minecraft\:calcite=\#e2dfd6
minecraft\:cherry_leaves=\#adb2de
minecraft\:cherry_planks=\#ffd7d4
minecraft\:chiseled_deepslate=\#363636
minecraft\:chiseled_nether_bricks=\#2e181c
minecraft\:chiseled_quartz_block=\#e5e0da
minecraft\:chorus_plant=\#7e5a7f
minecraft\:clay=\#9ea3ab
minecraft\:coal_block=\#0f0f0f
minecraft\:coarse_dirt=\#77553b
minecraft\:cobbled_deepslate=\#4a4a4f
minecraft\:cobblestone=\#757575
minecraft\:copper_block=\#c06c50
minecraft\:cracked_deepslate_tiles=\#343434
minecraft\:cracked_nether_bricks=\#2a161a
minecraft\:cracked_stone_bricks=\#7b7976
minecraft\:crimson_nylium=\#751f22
minecraft\:crimson_planks=\#6b3035
minecraft\:crying_obsidian=\#191130
minecraft\:cyan_concrete=\#157788
minecraft\:cyan_terracotta=\#565b5c
minecraft\:cyan_wool=\#169c9c
minecraft\:dark_oak_leaves=\#254622
minecraft\:dark_oak_log=\#3c2e1a
minecraft\:dark_oak_planks=\#432b14
minecraft\:dark_prismarine=\#2e5c5b
minecraft\:deepslate=\#4d4d52
minecraft\:deepslate_bricks=\#505055
minecraft\:deepslate_tiles=\#4e4e52
minecraft\:diamond_block=\#64e9dd
minecraft\:diorite=\#bcbcbc
minecraft\:dirt=\#866043
minecraft\:dried_kelp_block=\#34463a
minecraft\:dripstone_block=\#836f66
minecraft\:emerald_block=\#54d067
minecraft\:end_stone=\#dbdca3
minecraft\:end_stone_bricks=\#d4d4a7
minecraft\:exposed_copper=\#a17e68
minecraft\:gold_block=\#fad031
minecraft\:granite=\#956755
minecraft\:gravel=\#827d7a
minecraft\:gray_concrete=\#36393d
minecraft\:gray_terracotta=\#3a2a24
minecraft\:gray_wool=\#404040
minecraft\:green_concrete=\#495b24
minecraft\:green_terracotta=\#4c532a
minecraft\:green_wool=\#546d1b
minecraft\:hay_block=\#a88b19
minecraft\:iron_block=\#dcdcdc
minecraft\:jungle_leaves=\#255e25
minecraft\:jungle_planks=\#a07143
minecraft\:lapis_block=\#213a8a
minecraft\:light_blue_concrete=\#2489c7
minecraft\:light_blue_terracotta=\#716d8a
minecraft\:light_blue_wool=\#3aafd9
minecraft\:light_gray_concrete=\#7d7d73
minecraft\:light_gray_terracotta=\#876b62
minecraft\:light_gray_wool=\#a4a8b8
minecraft\:lime_concrete=\#5ea818
minecraft\:lime_terracotta=\#677635
minecraft\:lime_wool=\#70b919
minecraft\:magenta_concrete=\#a9309f
minecraft\:magenta_terracotta=\#96586d
minecraft\:magenta_wool=\#be44be
minecraft\:mangrove_leaves=\#305e27
minecraft\:mangrove_planks=\#613b27
minecraft\:melon=\#699233
minecraft\:moss_block=\#596d2d
minecraft\:mossy_cobblestone=\#6a745e
minecraft\:mossy_stone_bricks=\#6c7660
minecraft\:mud=\#3c2b1b
minecraft\:mud_bricks=\#5c4433
minecraft\:mushroom_stem=\#cecabe
minecraft\:nether_bricks=\#2c1619
minecraft\:nether_wart_block=\#730b19
minecraft\:netherite_block=\#423d41
minecraft\:netherrack=\#6c3131
minecraft\:oak_leaves=\#306030
minecraft\:oak_planks=\#a2824f
minecraft\:obsidian=\#13101b
minecraft\:orange_concrete=\#e06100
minecraft\:orange_terracotta=\#a25426
minecraft\:orange_wool=\#f07613
minecraft\:oxidized_copper=\#52a385
minecraft\:packed_mud=\#85694a
minecraft\:pink_concrete=\#d6658f
minecraft\:pink_terracotta=\#a24e4f
minecraft\:pink_wool=\#ed8dac
minecraft\:podzol=\#795331
minecraft\:polished_andesite=\#8c8c8d
minecraft\:polished_basalt=\#5a5a60
minecraft\:polished_deepslate=\#525256
minecraft\:polished_diorite=\#c0c0c0
minecraft\:polished_granite=\#9a6c5a
minecraft\:prismarine=\#63a8a0
minecraft\:prismarine_bricks=\#69aa98
minecraft\:pumpkin=\#c37917
minecraft\:purple_concrete=\#64209c
minecraft\:purple_terracotta=\#764656
minecraft\:purple_wool=\#792aac
minecraft\:purpur_block=\#a980aa
minecraft\:purpur_pillar=\#a47ca5
minecraft\:quartz_block=\#ece9e2
minecraft\:red_concrete=\#8e2020
minecraft\:red_mushroom_block=\#b23936
minecraft\:red_nether_bricks=\#481412
minecraft\:red_sand=\#be6639
minecraft\:red_sandstone=\#bd6948
minecraft\:red_terracotta=\#8f3d2f
minecraft\:red_wool=\#a02722
minecraft\:redstone_block=\#be2311
minecraft\:rooted_dirt=\#856042
minecraft\:sand=\#dad29e
minecraft\:sandstone=\#d8d2ae
minecraft\:sculk=\#0c1d24
minecraft\:smooth_basalt=\#68686e
minecraft\:smooth_quartz=\#e5e1d9
minecraft\:smooth_stone=\#9e9e9e
minecraft\:snow_block=\#f0f5fa
minecraft\:soul_sand=\#4e3a2a
minecraft\:soul_soil=\#4d3c34
minecraft\:sponge=\#c3c354
minecraft\:spruce_leaves=\#274626
minecraft\:spruce_log=\#3a2510
minecraft\:spruce_planks=\#725430
minecraft\:stone=\#7d7d7d
minecraft\:stone_bricks=\#7b7b7b
minecraft\:stripped_dark_oak_log=\#483824
minecraft\:terracotta=\#985f43
minecraft\:tuff=\#68655e
minecraft\:warped_nylium=\#265957
minecraft\:warped_planks=\#235058
minecraft\:warped_wart_block=\#167779
minecraft\:weathered_copper=\#6c996e
minecraft\:wet_sponge=\#9eac53
minecraft\:white_concrete=\#cfd5d6
minecraft\:white_terracotta=\#d1b2a1
minecraft\:white_wool=\#e9ecec
minecraft\:yellow_concrete=\#f1af15
minecraft\:yellow_terracotta=\#ba8523
minecraft\:yellow_wool=\#f8c627
